<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE mods [
    <!ELEMENT mods (mod*)>
    <!ATTLIST mods format         CDATA #REQUIRED
                   name           CDATA "ModsParam.xml"
                   description    CDATA "CM3D2.AddModsSlider.Plugin の各modスライダーのパラメータ定義用XML">
    <!ELEMENT mod (value*)>
    <!ATTLIST mod id              CDATA #REQUIRED
                  description     CDATA ""
                  type            CDATA "slider"
                  on_wideslider   CDATA "false"
                  visible         CDATA "true">
    <!ELEMENT value EMPTY>
    <!ATTLIST value prop_name     CDATA #REQUIRED
                    min           CDATA "0"
                    max           CDATA "10"
                    label         CDATA ""
                    type          CDATA "num"
                    default       CDATA "0"
                    visible       CDATA "true">
] >

<!--
    設置場所 : \CM3D2\UnityInjector\Config\ModsParam.xml

    書式説明 : CM3D2.AddModsSlider.Plugin.0.1.1.8 以降に対応

    <mod id="EYEBALL"                    : 必須。modの識別名。拡張セーブデータを参照。
         description="..."               : 省略可。規定値は空白。modの説明。
         type="slider"                   : 省略可。規定値は"slider"。"toggle"で<value />タグ不要のトグルボタンに。
         on_wideslider="false"           : 省略可。規定値は"false"。"true"指定するとWIDESLIDER無効時に非表示になる。WIDESLIDER前提のmod用。
         visible="true"                  : 省略可。規定値は"true"。"false"指定でこのmodのスライダーを表示させない。
    >
    
        <value prop_name="EYEBALL.width" : 必須。valueの識別名。拡張セーブデータを参照。
               min="0.1"                 : 省略可。規定値は"0"。スライダーの最小値。
               max="2.0"                 : 省略可。規定値は"10"。スライダーの最大値。
               label="横"                : 省略可。規定値は空白。スライダーのラベル。
               type="scale"              : 省略可。規定値は"num"。「倍率」なら"scale"。「整数値」なら"int"。
               default="1.0"          	 : 省略可。規定値は"0"(type="scale"の時は"1")。valueの初期値。
               visible="true"            : 省略可。規定値は"true"。"false"指定でこのvalueのスライダーを表示させない。
        />

        <value prop_name="EYEBALL.height" min="0.1" max="2.0" label="縦" type="scale" />
                                         : <value ... /> の一行表記。

        ...                              : modが必要とする入力数値分だけ、 <value ... /> を記載する。
    </mod>
-->


<mods format="1.2" name="ModsParam.xml"
      description="CM3D2.AddModsSlider.Plugin の各modスライダーのパラメータ定義用XML">

    <mod id="WIDESLIDER" description ="スライダー拡張" type="toggle" />
    <mod id="PROPSET_OFF" description ="@PropSet補正停止" type="toggle" />
    <mod id="LIPSYNC_OFF" description ="口パク停止" type="toggle" />
    <mod id="HYOUJOU_OFF" description ="表情変化停止" type="toggle" />
    <mod id="EYETOCAMERA_OFF" description ="@EyeToCamera視線切替停止" type="toggle" />
    <mod id="MUHYOU" description ="全ての顔処理を停止" type="toggle" />
    <mod id="FARMFIX" description ="前腕の歪み修正" on_wideslider="true" type="toggle" />
    <mod id="FACE_OFF" description ="@Faceによる表情変化抑制" type="toggle" />
    <mod id="FACEBLEND_OFF" description ="@FaceBlendによる表情変化抑制" type="toggle" />

    <mod id="EYETOCAM" description ="目をカメラに向ける" >
        <value prop_name="EYETOCAM" min="-1" max="1" label="数値" type="int" />
    </mod>
    
    <mod id="HEADTOCAM" description ="顔をカメラに向ける" >
        <value prop_name="HEADTOCAM" min="-1" max="1" label="数値" type="int" />
    </mod>

    <mod id="PITCH" description ="声のピッチ" >
        <value prop_name="PITCH" min="-1" max="1" label="数値" type="num" />
    </mod>

    <mod id="MABATAKI" description ="目の開度" >
        <value prop_name="MABATAKI" min="0" max="1.0" label="数値" type="num" />
    </mod>

    <mod id="LIPSYNC_INTENISTY" description="リップシンク強度指定" >
        <value prop_name="LIPSYNC_INTENISTY.value" min="0.0" max="1.0" label="数値" type="num" />
    </mod>

    <mod id="EYEBALL" description="瞳の大きさ" >
        <value prop_name="EYEBALL.width" min="0.1" max="2.0" label="横" type="scale" />
        <value prop_name="EYEBALL.height" min="0.1" max="2.0" label="縦" type="scale" />
    </mod>

    <mod id="EYE_RATIO" description="目の縦横比率" on_wideslider="true" >
        <value prop_name="EYE_RATIO" min="0.1" max="2.0" label="比率" type="scale" />
    </mod>

    <mod id="EYE_ANG" description="目の角度" on_wideslider="true" >
        <value prop_name="EYE_ANG.angle" min="-60" max="60" label="角度" type="num" />
        <value prop_name="EYE_ANG.x" min="-200" max="200" label="縦補正" type="num" />
        <value prop_name="EYE_ANG.y" min="-200" max="200" label="横補正" type="num" />
    </mod>

    <mod id="PELSCL" description="骨盤スケーリング" on_wideslider="true" >
        <value prop_name="PELSCL.width" min="0.1" max="2.0" label="横幅" type="scale" />
        <value prop_name="PELSCL.depth" min="0.1" max="2.0" label="奥行" type="scale" />
        <value prop_name="PELSCL.height" min="0.1" max="2.0" label="高さ" type="scale" />
    </mod>

    <mod id="THISCL" description="足全体のスケーリング"  on_wideslider="true" >
        <value prop_name="THISCL.width" min="0.1" max="2.0" label="横幅" type="scale" />
        <value prop_name="THISCL.depth" min="0.1" max="2.0" label="奥行" type="scale" />
    </mod>

    <mod id="THIPOS" description="足の位置"  on_wideslider="true" >
        <value prop_name="THIPOS.x" min="-100" max="200" label="左右" type="num" />
        <value prop_name="THIPOS.z" min="-100" max="200" label="前後" type="num" />
    </mod>

    <mod id="SKTSCL" description="スカート周辺スケーリング" on_wideslider="true">
        <value prop_name="SKTSCL.width"  min="0.1" max="3.0" label="横幅" type="scale" />
        <value prop_name="SKTSCL.depth"  min="0.1" max="3.0" label="奥行" type="scale" />
        <value prop_name="SKTSCL.height" min="0.1" max="3.0" label="高さ" type="scale" />
    </mod>

    <mod id="SPISCL" description="胴(下腹部)スケーリング" on_wideslider="true">
        <value prop_name="SPISCL.width"  min="0.1" max="3.0" label="横幅" type="scale" />
        <value prop_name="SPISCL.depth"  min="0.1" max="3.0" label="奥行" type="scale" />
        <value prop_name="SPISCL.height" min="0.1" max="3.0" label="高さ" type="scale" />
    </mod>

    <mod id="S0ASCL" description="胴(腹部)スケーリング" on_wideslider="true">
        <value prop_name="S0ASCL.width"  min="0.1" max="3.0" label="横幅" type="scale" />
        <value prop_name="S0ASCL.depth"  min="0.1" max="3.0" label="奥行" type="scale" />
        <value prop_name="S0ASCL.height" min="0.1" max="3.0" label="高さ" type="scale" />
    </mod>

    <mod id="S1_SCL" description="胴(みぞおち)スケーリング" on_wideslider="true">
        <value prop_name="S1_SCL.width"  min="0.1" max="3.0" label="横幅" type="scale" />
        <value prop_name="S1_SCL.depth"  min="0.1" max="3.0" label="奥行" type="scale" />
        <value prop_name="S1_SCL.height" min="0.1" max="3.0" label="高さ" type="scale" />
    </mod>

    <mod id="S1ASCL" description="胴(肋骨)スケーリング" on_wideslider="true">
        <value prop_name="S1ASCL.width"  min="0.1" max="3.0" label="横幅" type="scale" />
        <value prop_name="S1ASCL.depth"  min="0.1" max="3.0" label="奥行" type="scale" />
        <value prop_name="S1ASCL.height" min="0.1" max="3.0" label="高さ" type="scale" />
    </mod>

</mods>